### ISSUE TITLE
Write Correlation

### ISSUE THREAD

**Issue by chl9430** [Seok93/fibonacci-chicken#3]
Write the correlation between chicken and Fibonacci numbers.

##Task list

- [ ] write the correlation between chicken and Fibonacci numbers.

**Comment by Seok93** [comment]
이슈 내용물이 없어요 채워주세요

**Comment by chl9430** [comment]
썼습니다...

**Comment by chl9430** [comment]
> 이슈 내용물이 없어요 채워주세요

작성하였습니다...😅
